/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import BaseDatos.MesaData;
import Entidades.Mesa;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Hogar
 */
public class Salon extends javax.swing.JInternalFrame {

    Icon icoR = new ImageIcon(getClass().getResource("/Recursos/mesa-rojo.png"));
    Icon icoV = new ImageIcon(getClass().getResource("/Recursos/mesa-verde.png"));
    Icon icoG = new ImageIcon(getClass().getResource("/Recursos/mesa-gris.png"));
    MesaData md = new MesaData();
    List<Mesa> mesas = md.listarMesas();
    Mesa mes = new Mesa();
    private boolean mesaOcupada = false;


    
    /**
     * Creates new form Salon
     */
    public Salon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mesa9 = new javax.swing.JLabel();
        mesa29 = new javax.swing.JLabel();
        mesa3 = new javax.swing.JLabel();
        mesa8 = new javax.swing.JLabel();
        mesa22 = new javax.swing.JLabel();
        mesa24 = new javax.swing.JLabel();
        mesa6 = new javax.swing.JLabel();
        mesa20 = new javax.swing.JLabel();
        mesa30 = new javax.swing.JLabel();
        mesa2 = new javax.swing.JLabel();
        mesa21 = new javax.swing.JLabel();
        mesa14 = new javax.swing.JLabel();
        mesa13 = new javax.swing.JLabel();
        mesa27 = new javax.swing.JLabel();
        mesa1 = new javax.swing.JLabel();
        mesa7 = new javax.swing.JLabel();
        mesa26 = new javax.swing.JLabel();
        mesa16 = new javax.swing.JLabel();
        mesa28 = new javax.swing.JLabel();
        mesa25 = new javax.swing.JLabel();
        mesa4 = new javax.swing.JLabel();
        mesa11 = new javax.swing.JLabel();
        mesa18 = new javax.swing.JLabel();
        mesa19 = new javax.swing.JLabel();
        mesa10 = new javax.swing.JLabel();
        mesa17 = new javax.swing.JLabel();
        mesa5 = new javax.swing.JLabel();
        mesa15 = new javax.swing.JLabel();
        mesa12 = new javax.swing.JLabel();
        mesa23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setPreferredSize(new java.awt.Dimension(900, 718));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mesa9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa9.setText("9");
        mesa9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa9MouseClicked(evt);
            }
        });
        jPanel1.add(mesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        mesa29.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa29.setText("29");
        mesa29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa29MouseClicked(evt);
            }
        });
        jPanel1.add(mesa29, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        mesa3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa3.setText("3");
        mesa3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa3MouseClicked(evt);
            }
        });
        jPanel1.add(mesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        mesa8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa8.setText("8");
        mesa8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa8MouseClicked(evt);
            }
        });
        jPanel1.add(mesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        mesa22.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa22.setText("22");
        mesa22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa22MouseClicked(evt);
            }
        });
        jPanel1.add(mesa22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        mesa24.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa24.setText("24");
        mesa24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa24MouseClicked(evt);
            }
        });
        jPanel1.add(mesa24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));

        mesa6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa6.setText("6");
        mesa6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa6MouseClicked(evt);
            }
        });
        jPanel1.add(mesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        mesa20.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa20.setText("20");
        mesa20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa20MouseClicked(evt);
            }
        });
        jPanel1.add(mesa20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        mesa30.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa30.setText("30");
        mesa30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa30MouseClicked(evt);
            }
        });
        jPanel1.add(mesa30, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, -1, -1));

        mesa2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa2.setText("2");
        mesa2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa2MouseClicked(evt);
            }
        });
        jPanel1.add(mesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        mesa21.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa21.setText("21");
        mesa21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa21MouseClicked(evt);
            }
        });
        jPanel1.add(mesa21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        mesa14.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa14.setText("14");
        mesa14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa14MouseClicked(evt);
            }
        });
        jPanel1.add(mesa14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        mesa13.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa13.setText("13");
        mesa13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa13MouseClicked(evt);
            }
        });
        jPanel1.add(mesa13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        mesa27.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa27.setText("27");
        mesa27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa27MouseClicked(evt);
            }
        });
        jPanel1.add(mesa27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        mesa1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa1.setText("1");
        mesa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa1MouseClicked(evt);
            }
        });
        jPanel1.add(mesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        mesa7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa7.setText("7");
        mesa7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa7MouseClicked(evt);
            }
        });
        jPanel1.add(mesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        mesa26.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa26.setText("26");
        mesa26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa26MouseClicked(evt);
            }
        });
        jPanel1.add(mesa26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        mesa16.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa16.setText("16");
        mesa16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa16MouseClicked(evt);
            }
        });
        jPanel1.add(mesa16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        mesa28.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa28.setText("28");
        mesa28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa28MouseClicked(evt);
            }
        });
        jPanel1.add(mesa28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        mesa25.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa25.setText("25");
        mesa25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa25MouseClicked(evt);
            }
        });
        jPanel1.add(mesa25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        mesa4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa4.setText("4");
        mesa4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa4MouseClicked(evt);
            }
        });
        jPanel1.add(mesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        mesa11.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa11.setText("11");
        mesa11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa11MouseClicked(evt);
            }
        });
        jPanel1.add(mesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        mesa18.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa18.setText("18");
        mesa18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa18MouseClicked(evt);
            }
        });
        jPanel1.add(mesa18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        mesa19.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa19.setText("19");
        mesa19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa19MouseClicked(evt);
            }
        });
        jPanel1.add(mesa19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        mesa10.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa10.setText("10");
        mesa10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa10MouseClicked(evt);
            }
        });
        jPanel1.add(mesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        mesa17.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa17.setText("17");
        mesa17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa17MouseClicked(evt);
            }
        });
        jPanel1.add(mesa17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        mesa5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa5.setText("5");
        mesa5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa5MouseClicked(evt);
            }
        });
        jPanel1.add(mesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        mesa15.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa15.setText("15");
        mesa15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa15MouseClicked(evt);
            }
        });
        jPanel1.add(mesa15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        mesa12.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa12.setText("12");
        mesa12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa12MouseClicked(evt);
            }
        });
        jPanel1.add(mesa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        mesa23.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mesa23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-icon.png"))); // NOI18N
        mesa23.setText("23");
        mesa23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mesa23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesa23MouseClicked(evt);
            }
        });
        jPanel1.add(mesa23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ico pedido/anular_48.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 40));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salon.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1000, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mesa9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa9MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa9.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa9= new Mesa();

        } else{

            mesa9.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa9MouseClicked

    private void mesa29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa29MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa29.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa29= new Mesa();

        } else{

            mesa29.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa29MouseClicked

    private void mesa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa3MouseClicked
        // Cambia el estado de la mesa
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa3.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa3= new Mesa();

        } else{

            mesa3.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa3MouseClicked

    private void mesa8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa8MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa8.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa8= new Mesa();

        } else{

            mesa8.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa8MouseClicked

    private void mesa22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa22MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa22.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa22= new Mesa();

        } else{

            mesa22.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa22MouseClicked

    private void mesa24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa24MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa24.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa24= new Mesa();

        } else{

            mesa24.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa24MouseClicked

    private void mesa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa6MouseClicked
        // TODO add your handling code here:
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa6.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa6= new Mesa();

        } else{

            mesa6.setIcon(icoG); // Cambia el color al libre

        }

    }//GEN-LAST:event_mesa6MouseClicked

    private void mesa20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa20MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa20.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa20= new Mesa();

        } else{

            mesa20.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa20MouseClicked

    private void mesa30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa30MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa30.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa30= new Mesa();

        } else{

            mesa30.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa30MouseClicked

    private void mesa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa2MouseClicked
        // Cambia el estado de la mesa
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa2.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa2 = new Mesa();

        } else{

            mesa2.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa2MouseClicked

    private void mesa21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa21MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa21.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa21= new Mesa();

        } else{

            mesa21.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa21MouseClicked

    private void mesa14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa14MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa14.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa14= new Mesa();

        } else{

            mesa14.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa14MouseClicked

    private void mesa13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa13MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa13.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa13= new Mesa();

        } else{

            mesa13.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa13MouseClicked

    private void mesa27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa27MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa27.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa27= new Mesa();

        } else{

            mesa27.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa27MouseClicked

    private void mesa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa1MouseClicked

        // Cambia el estado de la mesa
        mesaOcupada = !mesaOcupada;

         // Actualiza el color de fondo
        if (mesaOcupada){

            mesa1.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa1 = new Mesa();

        } else{

            mesa1.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa1MouseClicked

    private void mesa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa7MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa7.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa7= new Mesa();

        } else{

            mesa7.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa7MouseClicked

    private void mesa26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa26MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa26.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa26= new Mesa();

        } else{

            mesa26.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa26MouseClicked

    private void mesa16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa16MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa16.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa16= new Mesa();

        } else{

            mesa16.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa16MouseClicked

    private void mesa28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa28MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa28.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa28= new Mesa();

        } else{

            mesa28.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa28MouseClicked

    private void mesa25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa25MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa25.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa25= new Mesa();

        } else{

            mesa25.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa25MouseClicked

    private void mesa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa4MouseClicked

        // Cambia el estado de la mesa
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa4.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa4= new Mesa();

        } else{

            mesa4.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa4MouseClicked

    private void mesa11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa11MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa11.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa11= new Mesa();

        } else{

            mesa11.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa11MouseClicked

    private void mesa18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa18MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa18.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa18= new Mesa();

        } else{

            mesa18.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa18MouseClicked

    private void mesa19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa19MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa19.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa19= new Mesa();

        } else{

            mesa19.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa19MouseClicked

    private void mesa10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa10MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa10.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa10Mesa= new Mesa();

        } else{

            mesa10.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa10MouseClicked

    private void mesa17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa17MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa17.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa17= new Mesa();

        } else{

            mesa17.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa17MouseClicked

    private void mesa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa5MouseClicked

        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa5.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa5= new Mesa();

        } else{

            mesa5.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa5MouseClicked

    private void mesa15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa15MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa15.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa15= new Mesa();

        } else{

            mesa15.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa15MouseClicked

    private void mesa12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa12MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa12.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa12= new Mesa();

        } else{

            mesa12.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa12MouseClicked

    private void mesa23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesa23MouseClicked
        mesaOcupada = !mesaOcupada;

        // Actualiza el color de fondo
        if (mesaOcupada){

            mesa23.setIcon(icoR); // Cambia el color al ocupado
            Mesa mesa23= new Mesa();

        } else{

            mesa23.setIcon(icoG); // Cambia el color al libre

        }
    }//GEN-LAST:event_mesa23MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked


        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mesa1;
    private javax.swing.JLabel mesa10;
    private javax.swing.JLabel mesa11;
    private javax.swing.JLabel mesa12;
    private javax.swing.JLabel mesa13;
    private javax.swing.JLabel mesa14;
    private javax.swing.JLabel mesa15;
    private javax.swing.JLabel mesa16;
    private javax.swing.JLabel mesa17;
    private javax.swing.JLabel mesa18;
    private javax.swing.JLabel mesa19;
    private javax.swing.JLabel mesa2;
    private javax.swing.JLabel mesa20;
    private javax.swing.JLabel mesa21;
    private javax.swing.JLabel mesa22;
    private javax.swing.JLabel mesa23;
    private javax.swing.JLabel mesa24;
    private javax.swing.JLabel mesa25;
    private javax.swing.JLabel mesa26;
    private javax.swing.JLabel mesa27;
    private javax.swing.JLabel mesa28;
    private javax.swing.JLabel mesa29;
    private javax.swing.JLabel mesa3;
    private javax.swing.JLabel mesa30;
    private javax.swing.JLabel mesa4;
    private javax.swing.JLabel mesa5;
    private javax.swing.JLabel mesa6;
    private javax.swing.JLabel mesa7;
    private javax.swing.JLabel mesa8;
    private javax.swing.JLabel mesa9;
    // End of variables declaration//GEN-END:variables
}
